### PR TITLE
JS module support, bug fixes and animationTime

### PR DESCRIPTION
**Pull request by oizulain**
**Additions:**
- AMD and Node/CommonJS module support.
- Ability to customize animation time.

**Bug fixes and corrections:**
- Prevents listener from firing when initializing drop down.
- Adds the close drop down listener only once. Before, the close body click listener was added for every drop down on the site.
- Respecting the drop down holder id, it seems wrong to change the drop down element id. Some devs have complained about this before. For instance, if `#myHolder` is changed to `#myHolder-dd-placeholder` after calling `$("#myHolder").ddslick();`, then `$("#myHolder").destroy();` won't work.

### CODE REVIEW

**Comment by ChunkRadius** [comment]
@oizulain Thanks!

**Comment by oizulain** [comment]
@bradberger Thanks to you for merging so fast!

**Comment by oizulain** [comment]
@bradberger Could you create a 1.0.2 tag and publish on npm?

**Comment by ChunkRadius** [comment]
No problem, published it now.

**Comment by ChunkRadius** [comment]
@oizulain If you're interested in maintaining this long-term let me know. It's not really being actively developed so having someone who can push updates like this would be great.

**Comment by oizulain** [comment]
@bradberger Ok! I'm happy to contribute with any improvements that we might need or discuss/merge PRs if someone creates them.

**Pull request merged**
